#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    Apr 21, 2021 11:10:20 PM IDT  platform: Linux

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import client_gui as trivia_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = first_page(root)
    trivia_support.init(root, top)
    root.mainloop()


w = None
w_win = None


def create_first_page(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_first_page(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = first_page(w)
    trivia_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_first_page():
    global w
    w.destroy()
    w = None


class first_page:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("450x276+454+160")
        top.minsize(1, 1)
        top.maxsize(1345, 633)
        top.resizable(0, 0)
        top.title("Trivia Game")
        top.configure(highlightcolor="black")

        self.usernameLabelframe = tk.LabelFrame(top)
        self.usernameLabelframe.place(relx=0.067, rely=0.174, relheight=0.163
                                      , relwidth=0.911)
        self.usernameLabelframe.configure(relief='groove')
        self.usernameLabelframe.configure(text='''Username''')

        self.usernameEntry = tk.Entry(self.usernameLabelframe)
        self.usernameEntry.place(relx=0.024, rely=0.4, height=23, relwidth=0.941
                                 , bordermode='ignore')
        self.usernameEntry.configure(background="white")
        self.usernameEntry.configure(font="TkFixedFont")
        self.usernameEntry.configure(selectbackground="blue")
        self.usernameEntry.configure(selectforeground="white")

        self.passwordLabelframe1 = tk.LabelFrame(top)
        self.passwordLabelframe1.place(relx=0.067, rely=0.362, relheight=0.163
                                       , relwidth=0.911)
        self.passwordLabelframe1.configure(relief='groove')
        self.passwordLabelframe1.configure(text='''password''')

        self.passwordEntry = tk.Entry(self.passwordLabelframe1)
        self.passwordEntry.place(relx=0.024, rely=0.4, height=23, relwidth=0.941
                                 , bordermode='ignore')
        self.passwordEntry.configure(background="white")
        self.passwordEntry.configure(font="TkFixedFont")
        self.passwordEntry.configure(selectbackground="blue")
        self.passwordEntry.configure(selectforeground="white")
        self.passwordEntry.config(show="*")

        self.title = tk.Label(top)
        self.title.place(relx=0.067, rely=0.036, height=41, width=409)
        self.title.configure(activebackground="#f9f9f9")
        self.title.configure(text='''Trivia Game''')

        self.msgLabel = tk.Label(top)
        self.msgLabel.place(relx=0.067, rely=0.543, relheight=0.341
                            , relwidth=0.436)
        self.msgLabel.configure(activebackground="#f9f9f9")
        self.msgLabel.configure(text='''MSG FROM SERVER''')
        self.msgLabel.configure(wraplength=180)

        self.registerButton = tk.Button(top)
        self.registerButton.place(relx=0.791, rely=0.547, height=43, width=83)
        self.registerButton.configure(activebackground="#f9f9f9")
        self.registerButton.configure(borderwidth="2")
        self.registerButton.configure(command=trivia_support.register)
        self.registerButton.configure(text='''Register''')

        self.exitButton = tk.Button(top)
        self.exitButton.place(relx=0.791, rely=0.728, height=43, width=83)
        self.exitButton.configure(activebackground="#f9f9f9")
        self.exitButton.configure(borderwidth="2")
        self.exitButton.configure(command=trivia_support.quit_cmd)
        self.exitButton.configure(text='''EXIT''')

        self.loginButton = tk.Button(top)
        self.loginButton.place(relx=0.513, rely=0.547, height=93, width=123)
        self.loginButton.configure(borderwidth="2")
        self.loginButton.configure(command=trivia_support.login)
        self.loginButton.configure(text='''Login''')


if __name__ == '__main__':
    vp_start_gui()
